GROUP_REPOS = [
    [
        "group a",
        "ZeroDownTime",
        ["https://github.com/ZeroDownTime-ITU/minitwit_project"],
        "http://167.172.185.218:5173",
        "http://167.172.185.218:5173/api",
    ],
    [
        "group b",
        "Carl ⏰",
        ["https://github.com/DevOps-Group-B/MiniTwit"],
        "http://165.227.170.149",
        "http://165.227.170.149",
    ],
    [
        "group c",
        "youCanCUs",
        ["https://github.com/Anders0106/Devops2026"],
        "https://devops2026-production.up.railway.app",
        "https://devops2026-production.up.railway.app",
    ],
    [
        "group d",
        "Mixed",
        ["https://github.com/KaramTNC/itu-minitwit"],
        "http://165.22.66.118:5001",
        "http://46.101.201.186:8080",
    ],
    [
        "group e",
        "Jams",
        ["https://github.com/sebsthiel/minitwit-devops"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group f",
        "if time > 16 {beer++;}",
        ["https://github.com/TienCamLy/MiniTwit"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group g",
        "GruppeOG",
        ["https://git.marfavi.com/DevOpps/itu-minitwit-migration"],
        "http://142.93.169.145:7273/",
        "http://142.93.169.145:7273/",
    ],
    [
        "group i",
        "Team Connie",
        ["https://github.com/21Philip/devops-minitwit"],
        "http://146.190.204.218:5001",
        "http://146.190.204.218:5000",
    ],
    [
        "group j",
        "Chirp Vee2",
        ["https://github.com/ITU-DevOps-2026-J/Chirp-Vee2"],
        "http://157.245.27.199:8080/",
        "http://157.245.27.199:8080/",
    ],
    [
        "group k",
        "DevBobs",
        ["https://github.com/DevBobs-devops/Devbobs_MiniTwit"],
        "http://209.38.230.113:8080/",
        "http://209.38.230.113:8080/",
    ],
    [
        "group m",
        "Holy C Enjoyers",
        ["https://github.com/MudiLoodi/minitwit"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group n",
        "Diversity",
        ["https://github.com/huncut47/diversity"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group o",
        "Rollback & Relax",
        ["https://github.com/<organization|user>/<repository_name>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group a",
        "EastTops",
        ["https://github.com/AntohaY/itu-minitwit"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group q",
        "DevTroopers",
        ["https://github.com/DevTroopers-ITU/itu-minitwit"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group p",
        "rollback & relax",
        ["https://github.com/alqeren1/devops.git"],
        "http://ec2-13-51-198-31.eu-north-1.compute.amazonaws.com:3000/timeline",
        "http(s)://<TBA>/<APIURL>",
    ],
]
