GROUP_REPOS = [
    [
        "group a",
        "Ducks",
        ["https://github.com/Alexitu01/DevOps_Ducks"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group b",
        "Carl ⏰",
        ["https://github.com/DevOps-Group-B/MiniTwit"],
        "http://165.227.170.149",
        "http://165.227.170.149",
    ],
    [
        "group c",
        "youCanCUs",
        ["https://github.com/Anders0106/Devops2026"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group d",
        "Mixed",
        ["https://github.com/KaramTNC/itu-minitwit"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group e",
        "Disaster",
        ["https://github.com/Itu-DevOps-2026/ITU-MiniTwit"],
        "http://138.68.104.180:5000",
        "http://138.68.104.180:5000",
    ],
    [
        "group f",
        "Group 1",
        ["https://github.com/Afab1311/MiniTwit-gruppe1"],

        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group g",
        "GruppeOG",
        ["https://github.com/Joakim-David/GruppeOG"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group i",
        "Team Connie",
        ["https://github.com/21Philip/devops-minitwit"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group j",
        "Chirp Vee2",
        ["https://github.com/PokingPines/Chirp-Vee2"],
        "http://157.245.27.199:8080/",
        "http://157.245.27.199:8080/",
    ],
    [
        "group k",
        "DevBobs",
        ["https://github.com/mortfb/Devops_devBobs"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group l",
        "Deploy and pray",
        ["https://github.com/ITU-DEVOPS2026-GROUP-l/deploy_and_pray","https://github.com/ITU-DEVOPS2026-GROUP-l/ITU-MiniTwit"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group m",
        "Jackhammers",
        ["https://github.com/RonoITU/itu-devops2026-jackhammers"],
        "https://windysquirrels.dk/",
        "https://windysquirrels.dk/api/",
    ],
    [
        "group o",
        "No.1",
        ["https://github.com/YUMJiHyeon/DEVOPS"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
]
