GROUP_REPOS = [
    [
        "group a",
        "Ducks",
        ["https://github.com/Alexitu01/DevOps_Ducks.git>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group b",
        "Carl ⏰",
        ["https://github.com/DevOps-Group-B/MiniTwit.git"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group c",
        "youCanCUs",
        ["https://github.com/Anders0106/Devops2026"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group d",
        "Mixed",
        ["https://github.com/KaramTNC/itu-minitwit/tree/main"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group e",
        "Disaster",
        ["https://github.com/V0idshock/itu-minitwit-group-e"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group f",
        "if time > 16 {beer++}",
        ["https://github.com/TienCamLy/MiniTwit"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group g",
        "<name>",
        ["https://github.com/<organization|user>/<repository_name>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group h",
        "<name>",
        ["https://github.com/<organization|user>/<repository_name>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group i",
        "<name>",
        ["https://github.com/<organization|user>/<repository_name>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group j",
        "Chirp Vee2",
        ["https://github.com/PokingPines/Chirp-Vee2"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group k",
        "DevBobs",
        ["https://github.com/mortfb/Devops_devBobs"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group l",
        "<name>",
        ["https://github.com/<organization|user>/<repository_name>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group m",
        "<name>",
        ["https://github.com/<organization|user>/<repository_name>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group n",
        "Diversity",
        ["https://github.com/huncut47/diversity"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group o",
        "No.1",
        ["https://github.com/YUMJiHyeon/DEVOPS"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group p",
        "<name>",
        ["https://github.com/<organization|user>/<repository_name>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group q",
        "<name>",
        ["https://github.com/<organization|user>/<repository_name>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
]
